version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: KangaSys.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=kanga;Username=postgres;Password=password
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: KangaDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
